### ISSUE TITLE
I saw a crash when I add note in horizontal screen mode, But it no problem in vertical mode

### ISSUE THREAD

**Issue by hosseinkhojany** [yalda-student/note_to_remember#5]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Navigator-[LabeledGlobalKey<NavigatorState>#a2f5b](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope], state: NavigatorState#fc750(tickers: tracking 0 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5140 pos 12: '_history.isNotEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Navigator-[LabeledGlobalKey<NavigatorState>#a2f5b] Navigator:file:///home/khoujani/StudioProjects/student_note/lib/main.dart:216:11
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5140:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#9      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#10     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#14     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#18     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#20     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#27     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#37     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#42     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#46     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#49     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#50     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#54     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#56     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#57     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#62     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#66     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#71     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#77     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#79     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#82     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#84     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#87     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#89     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#93     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#97     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#100    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#102    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#106    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#109    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#111    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#114    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#116    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#117    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#118    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#119    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#120    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#121    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#125    _invoke (dart:ui/hooks.dart:151:10)
#126    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#127    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Navigator-[LabeledGlobalKey<NavigatorState>#a2f5b](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope], state: NavigatorState#fc750(tickers: tracking 0 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5140 pos 12: '_history.isNotEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Navigator-[LabeledGlobalKey<NavigatorState>#a2f5b] Navigator:file:///home/khoujani/StudioProjects/student_note/lib/main.dart:216:11
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5140:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#9      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#10     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#14     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#18     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#20     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#27     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#37     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#42     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#46     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#49     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#50     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#54     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#56     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#57     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#62     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#66     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#71     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#77     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#79     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#82     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#84     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#87     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#89     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#93     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#97     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#100    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#102    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#106    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#109    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#111    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#114    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#116    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#117    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#118    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#119    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#120    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#121    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#125    _invoke (dart:ui/hooks.dart:151:10)
#126    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#127    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================

**Comment by yalda-student** [comment]
Hi, thank you for the bug you report
