### ISSUE TITLE
the note list hasn't a divider between each other

### ISSUE THREAD

**Issue by hosseinkhojany** [yalda-student/note_to_remember#6]
![Screenshot from 2022-05-25 11-47-09](https://user-images.githubusercontent.com/37432839/170203509-e785f44b-65bd-4846-b6b7-2f9e9658d44c.png)
![Screenshot from 2022-05-25 11-47-03](https://user-images.githubusercontent.com/37432839/170203524-e0855948-7ee0-4b56-b550-d44cebb90053.png)

**Comment by yalda-student** [comment]
fixed in [change white color, and improvement in UI](https://github.com/yalda-student/student_note/commit/7ed63230456cac6e050a8fbcd40af9cab1614c49)](https://github.com/yalda-student/student_note/commit/7ed63230456cac6e050a8fbcd40af9cab1614c49)
